---
title: "Technologie Internetu Rzeczy"
subtitle: "Arduino"
author: "&copy; Łukasz Wawrowski"
date: ""
output:
  xaringan::moon_reader:
    css: ["default.css", "default-fonts.css"]
    lib_dir: libs
    nature:
      ratio: "4:3"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---

# Źródła wiedzy

- dokumentacja Arduino

- kurs Navoica np. [Internet Rzeczy](https://navoica.pl/courses/course-v1:Wyzsza_Szkola_Gospodarki_w_Bydgoszczy+WSG-03+2023_3/course/)

- [kurs Forbot](https://forbot.pl/blog/kurs-arduino-podstawy-programowania-spis-tresci-kursu-id5290)

- [tinkerpad](https://www.tinkercad.com/) - symulacja Arduino

- [wokwi](https://wokwi.com/) - symulator Arduino

- [Node-RED](https://nodered.org/) - low-code 

---

# Arduino Opla IoT Kit

- MKR Wifi 1010 Board

- MKR IoT Carrier

---

# Struktura programu Arduino

- `setup()`: Kod uruchamiany raz na początku.

- `loop()`: Kod wykonywany w pętli.

```cpp
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}

```

---

## Migająca dioda LED - przykład

```cpp
void setup() {
  pinMode(13, OUTPUT); // Ustaw pin 13 jako wyjście
}

void loop() {
  digitalWrite(13, HIGH); // Włącz diodę
  delay(1000);            // Czekaj 1 sekundę
  digitalWrite(13, LOW);  // Wyłącz diodę
  delay(1000);            // Czekaj 1 sekundę
}
```
---

# Migająca dioda

Wymagania:

- Arduino IDE

- Biblioteka WiFiNINA

- Arduino MKR WiFi 1010 (Board: Arduino SAMD Boards)

[Tutorial](https://docs.arduino.cc/tutorials/mkr-wifi-1010/built-in-rgb/)

---

class: inverse

```{r include=FALSE}
library(countdown)
```

`r countdown(minutes = 15, seconds = 0, top = 0)`

# Zadanie

Napisz program, który będzie symulował pracę sygnalizatora świetlnego dla pieszych - czerwone światło (10 sekund), zielone (8 sekund), migające zielone (2 sekundy). 

???

```cpp
#include <WiFiNINA.h> 
#include <utility/wifi_drv.h>

void setup() {
  // Definiowanie pinów dla diody RGB
  WiFiDrv::pinMode(25, OUTPUT); // Czerwony
  WiFiDrv::pinMode(26, OUTPUT); // Zielony 
  WiFiDrv::pinMode(27, OUTPUT); // Niebieski (nieużywany w tym przypadku)
}

void loop() {
  // Czerwone światło - 10 sekund
  WiFiDrv::analogWrite(25, 255);   // Zielony wyłączony
  WiFiDrv::analogWrite(26, 0); // Czerwony włączony
  WiFiDrv::analogWrite(27, 0);   // Niebieski wyłączony
  delay(10000);                  // Czekaj 10 sekund

  // Zielone światło - 8 sekund
  WiFiDrv::analogWrite(25, 0); // Zielony włączony
  WiFiDrv::analogWrite(26, 255);   // Czerwony wyłączony
  WiFiDrv::analogWrite(27, 0);   // Niebieski wyłączony
  delay(8000);                   // Czekaj 8 sekund

  // Migające zielone światło - 2 sekundy
  for (int i = 0; i < 5; i++) {  // 5 cykli po 400 ms
    WiFiDrv::analogWrite(26, 255); // Zielony włączony
    delay(200);                    // Włączony przez 200 ms
  
    WiFiDrv::analogWrite(26, 0);   // Zielony wyłączony
    delay(200);                    // Wyłączony przez 200 ms
    
  }
}
```

---

# Czujniki

Wymagania:

- Arduino IDE

- Biblioteka ArduinoMKRIoTCarrier

- Arduino MKR WiFi 1010 (Board: Arduino SAMD Boards) + MKR IoT Carrier

[Tutorial](https://docs.arduino.cc/tutorials/mkr-iot-carrier/mkr-iot-carrier-01-technical-reference/)

[Datasheet](https://content.arduino.cc/assets/MKR%20IoT%20Carrier%20-%20Datasheet.pdf)

---

# Inicjalizacja

```cpp
#include <Arduino_MKRIoTCarrier.h>

MKRIoTCarrier carrier;

void setup() {
  carrier.noCase(); // carrier.withCase();
  carrier.begin();
}


```

---

# Odczyt danych

```cpp
void loop() {

  float temperature = carrier.Env.readTemperature();
  float humidity = carrier.Env.readHumidity();

  Serial.println(temperature);
  Serial.println(humidity);

  delay(1000);
  
}
```

---

# Ekran

```cpp
  carrier.display.fillScreen(0x0000);
  carrier.display.setRotation(0); // 1,2,3
  carrier.display.setTextColor(0xFFFF);
  carrier.display.setTextSize(3);
  carrier.display.setCursor(120, 120); // 240 x 240
  carrier.display.print(temperature);

```

---

class: inverse

`r countdown(minutes = 15, seconds = 0, top = 0)`

# Zadanie

Napisz program, który powiąże poziom wilgotności powietrza z kolorem diod LED np. do 30% kolor zielony, a powyżej 30% kolor czerwony.

???

```cpp
uint32_t green = carrier.leds.Color(0,255,0);
uint32_t red = carrier.leds.Color(255,0,0);

carrier.leds.setBrightness(25);

if (humidity <= 40) {
  carrier.leds.fill(green, 0, 5);
} else {
  carrier.leds.fill(red, 0, 5);
}
carrier.leds.show();
```

---

class: inverse

`r countdown(minutes = 15, seconds = 0, top = 0)`

# Zadanie

Napisz program, który będzie zmieniał wyświetlane wartości czujników w zależności od wybranego przycisku.

???

```cpp
#include <Arduino_MKRIoTCarrier.h>

MKRIoTCarrier carrier;

int selectedSensor = 0; 

void setup() {

  carrier.noCase(); // carrier.withCase();
  carrier.begin();

}

void loop() {

  carrier.Buttons.update();

  if (carrier.Buttons.onTouchDown(TOUCH0)) {
    selectedSensor = 0; // Wilgotność
  } else if (carrier.Buttons.onTouchDown(TOUCH1)) {
    selectedSensor = 1; // Temperatura
  } else if (carrier.Buttons.onTouchDown(TOUCH3)) {
    selectedSensor = 2; // Ciśnienie
  }

  carrier.display.fillScreen(0x0000);
  carrier.display.setRotation(0); // 1,2,3
  carrier.display.setTextColor(0xFFFF);
  carrier.display.setTextSize(3);
  carrier.display.setCursor(20, 80); // 240 x 240

  switch (selectedSensor) {
    case 0: {
      float humidity = carrier.Env.readHumidity();
      carrier.display.println("Wilgotnosc: ");
      carrier.display.print("  ");
      carrier.display.print(humidity);
      carrier.display.print(" %");
      break;
    }
    case 1: {
      float temperature = carrier.Env.readTemperature();
      carrier.display.println("Temperatura: ");
      carrier.display.print("  ");
      carrier.display.print(temperature);
      carrier.display.print(" C");
      break;
    }
    case 2: {
      float pressure = carrier.Pressure.readPressure();
      carrier.display.println("Cisnienie: ");
      carrier.display.print("  ");
      carrier.display.print(pressure);
      carrier.display.print(" hPa");
      break;
    }
  }

  delay(1000);

}
```

---

# Czujnik ruchu

```cpp

void setup() {
  pinMode(A6, INPUT);
}

void loop() {
  Serial.println(digitalRead(A6));
}  

```

[Tutorial](https://arduinogetstarted.com/tutorials/arduino-motion-sensor)

---

class: center, middle, inverse

# Pytania?