---
title: "Technologie Internetu Rzeczy"
subtitle: "Projekt 1 - Packet Tracer"
format: pdf
---

Celem projektu jest wykorzystanie programu Cisco Packet Tracer do zaprojektowania rozwiązania smart home, smart city lub smart industry.

Projekt jest pracą grupową w zespołach 2-3 osobowych. Podstawą oceny jest sprawozdanie zawierające opis i uzasadnienie przeprowadzonych prac, plik programu Packet Tracer oraz prezentacja na zajęciach.

Projekt musi spełniać następujące wymagania:

- wykorzystanie różnych połączeń pomiędzy urządzeniami - co najmniej jednego typu bezprzewodowego i jednego typu przewodowego,

- stworzenie co najmniej dwóch nowych urządzeń IoT np. inteligentne drzwi dla zwierząt, automatyczne biurko (należy zweryfikować czy tworzone urządzenia już nie występują w programie PT),

- zmiana wartości zmiennych środowiskowych - co najmniej jedna wartość,

- uwzględnienie co najmniej czterech warunków wpływających na działanie urządzeń (bezpośrednio lub z wykorzystaniem MCU).

Spełnienie wymienionych wymagań w minimalnym stopniu skutkuje oceną dostateczną. Ocenie podlega także staranność wykonania projektu i sprawozdania oraz jakość prezentacji.
